[workspace]
channels = [
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge",
    "https://repo.huaweicloud.com/ascend/repos/conda"
]
name = "ResNet_Acl"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
extra-index-urls = ["https://mirrors.ustc.edu.cn/pypi/web/simple"]

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=26.0.1,<27"
ascend-cann-toolkit = "==8.5.0"
ascend-cann-310b-ops = "==8.5.0"
decorator = ">=5.2.1,<6"
sympy = ">=1.14.0,<2"
scipy = ">=1.17.1,<2"
attrs = ">=26.1.0,<27"
psutil = ">=7.2.2,<8"
matplotlib = ">=3.10.8,<4"
prettytable = ">=3.17.0,<4"
